name: Build and push with dynamic dockerfile
description: Generates a dockerfile to build legacy apps
inputs:
  deploy_key:
    required: true

defaults:
  run:
    shell: bash

runs:
  using: composite
  steps:
    - run: |
        mkdir -p -m 0600 ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        echo '${{ inputs.deploy_key }}' > .github

        ssh-agent bash -c 'echo "${{ inputs.deploy_key }}" | ssh-add -; git clone git@github.com:glg/ec2.starphleet.jobs.headquarters.git ./.github/jobs-hq'
      shell: bash
