name: Build and push with dynamic dockerfile
description: Generates a dockerfile to build legacy apps
inputs:
  access_key_id:
    required: true
  secret_access_key:
    required: true
  container_version:
    default: latest
  ecr_arn:
    required: true
  orders_name:
    required: true

runs:
  using: composite
  steps:
    - name: Setup environment
      run: |
        echo AWS_CONTAINER_CREDENTIALS_RELATIVE_URI='' >> $GITHUB_ENV
        echo AWS_REGION=$(cut --delimiter '.' --fields 4 <<< ${{ inputs.ecr_arn }}) >> $GITHUB_ENV
        echo DEPLOY_SSH_KEY_SECRET_NAME=gds/GLGUSER_PRIVATE_KEY >> $GITHUB_ENV
        echo HEADQUARTERS_BRANCH=master >> $GITHUB_ENV
        echo HEADQUARTERS_ORG=glg >> $GITHUB_ENV
        echo HEADQUARTERS_REPO=ec2.starphleet.jobs.headquarters >> $GITHUB_ENV
        echo ORDERS_NAME=${{ inputs.orders_name }} >> $GITHUB_ENV

        ECR_HOST=$(cut --delimiter '/' --fields 1 <<< "${{ inputs.ecr_arn }}")

        echo BASE_CONTAINER_IMAGE=$ECR_HOST/github/glg/gds-containerize-sanitized/main >> $GITHUB_ENV
        echo REPOSITORY_ARN=${{ inputs.ecr_arn }} >> $GITHUB_ENV
      shell: bash
    - run: env
      shell: bash
    - name: Login to Docker
      shell: bash
      run: |
        AWS_ACCESS_KEY_ID="${{inputs.access_key_id}}" \
        AWS_SECRET_ACCESS_KEY="${{inputs.secret_access_key}}" \
          aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin ${{ inputs.ecr_arn }}
    - name: build image
      run: |
        docker run \
          -i \
          --env ORDERS_NAME \
          --env HEADQUARTERS_BRANCH \
          --env HEADQUARTERS_ORG \
          --env HEADQUARTERS_REPO \
          --env DEPLOY_SSH_KEY_SECRET_NAME \
          --env AWS_CONTAINER_CREDENTIALS_RELATIVE_URI \
          --env AWS_ACCESS_KEY_ID="${{inputs.access_key_id}}" \
          --env AWS_SECRET_ACCESS_KEY="${{inputs.secret_access_key}}" \
          --init \
          --name build \
          "${BASE_CONTAINER_IMAGE}:${{ inputs.container_version }}" \
          build
      shell: bash
    - run: |
        docker commit \
          --change 'CMD ["/home/ubuntu/start", "web"]' \
          --change 'ENTRYPOINT ["./entrypoint.sh"]' \
          --change 'ENV AWS_ACCESS_KEY_ID=""' \
          --change 'ENV AWS_SECRET_ACCESS_KEY=""' \
          build $REPOSITORY_ARN:latest
      shell: bash
    - name: Tag and push
      run: |
        docker tag $REPOSITORY_ARN:latest $REPOSITORY_ARN:${{ github.sha }}
        docker push $REPOSITORY_ARN:${{ github.sha }}
        docker push $REPOSITORY_ARN:latest
      shell: bash
