name: Build and push with dynamic dockerfile
description: Generates a dockerfile to build legacy apps
inputs:
  access_key_id:
    required: true
  secret_access_key:
    required: true
  container_version:
    default: 436f00aecb934dc4f91ef95b07581c01352282cb
  ecr_host:
    required: true
  ecr_uri:
    required: true
  orders_name:
    required: true

defaults:
  run:
    shell: bash

runs:
  using: composite
  steps:
    - name: Setup environment
      run: |
        echo DEPLOY_SSH_KEY_SECRET_NAME=gds/GLGUSER_PRIVATE_KEY >> $GITHUB_ENV
        echo HEADQUARTERS_BRANCH=master >> $GITHUB_ENV
        echo HEADQUARTERS_ORG=glg >> $GITHUB_ENV
        echo HEADQUARTERS_REPO=ec2.starphleet.jobs.headquarters >> $GITHUB_ENV
        echo ORDERS_NAME=${{ inputs.orders_name }} >> $GITHUB_ENV
        echo AWS_CONTAINER_CREDENTIALS_RELATIVE_URI='' >> $GITHUB_ENV

        echo BASE_CONTAINER_IMAGE=${{ inputs.ecr_host }}/github/glg/gds-containerize/main >> $GITHUB_ENV
        echo REPOSITORY_URI=${{ inputs.ecr_host }}/github/glg/hq-stale/legacy-job-containerize >> $GITHUB_ENV
      shell: bash
    - run: env
      shell: bash
    - name: Login to Docker
      shell: bash
      run: |
        AWS_REGION=$(echo "${{ inputs.ecr_host }}" | cut -f4 -d'.')
        AWS_ACCESS_KEY_ID="${{inputs.access_key_id}}" \
        AWS_SECRET_ACCESS_KEY="${{inputs.secret_access_key}}" \
          aws ecr get-login-password --region "${AWS_REGION}" | docker login --username AWS --password-stdin ${{ inputs.ecr_uri }}
    - name: build image
      run: |
        docker run \
          -i \
          --env ORDERS_NAME \
          --env HEADQUARTERS_BRANCH \
          --env HEADQUARTERS_ORG \
          --env HEADQUARTERS_REPO \
          --env DEPLOY_SSH_KEY_SECRET_NAME \
          --env AWS_CONTAINER_CREDENTIALS_RELATIVE_URI \
          --init \
          --name "build" \
          "${BASE_CONTAINER_IMAGE}:${{ inputs.container_version }}" \
          build
      shell: bash
    - run: |
        docker commit \
          --change 'CMD ["/home/ubuntu/start","web"]' \
          "build" \
          "$ORDERS_NAME"
      shell: bash
    - run: docker tag "$ORDERS_NAME" "$REPOSITORY_URI:latest"
      shell: bash
    # - run: docker tag "$ORDERS_NAME" "$REPOSITORY_URI:$IMAGE_TAG"
